sudo: required
services:
- docker
install:
- docker build -t $BUILDING .
script:
- docker run -v $TRAVIS_BUILD_DIR/__tests__/mock:/var/www/__tests__/mock/:ro --rm
  -it $BUILDING npm test
deploy:
  provider: script
  script:
    - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
    - |
      if [ -n "$TRAVIS_TAG" ]; then
        docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_TAG;
        docker push $DOCKER_IMAGE:$TRAVIS_TAG;
      fi
    - docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_BRANCH
    - docker push $DOCKER_IMAGE:$TRAVIS_BRANCH
  on:
    tags: true
    all_branches: true

env:
  global:
  - DOCKER_IMAGE=idigbio/idigbio-search-api
  - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT
notifications:
  slack:
    secure: hBdS1mIVFVg8jTQwU2nXKyfLRPbUMYCQK0g+NEjkSvWl3hvAnZREGo2JBFgincdB2/wAJhuynBQXN7MSwxGm4jTjvTrs1SOPP7hssTr+xFrXuOs9tYDNLICcUmc8iIkt9oblw/jWCKHUDnphmcZ4sy3uJDuxuKGHdBjXYAq/eZw=
